spring.application.name=demo

# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}

# Cashfree Config
cashfree.app-id=${CASHFREE_APP_ID}
cashfree.secret-key=${CASHFREE_SECRET_KEY}
cashfree.api-url=${CASHFREE_API_URL}
cashfree.api-version=${CASHFREE_API_VERSION}

# Limit DB connections for free hosting
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
