spring.application.name=demo

# Database
spring.datasource.url=${DATABASE_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=${PORT:8080}

# Cashfree Config
cashfree.app-id=${CASHFREE_APP_ID}
cashfree.secret-key=${CASHFREE_SECRET_KEY}
cashfree.api-url=${CASHFREE_API_URL}
cashfree.api-version=${CASHFREE_API_VERSION}
